api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]

    formats:
        jsonld: [ 'application/ld+json', ]
        json: [ 'application/json' , 'application/merge-patch+json' ]

    collection:
        pagination:
            page_parameter_name: _page
            items_per_page_parameter_name: _show
